# PG setup:
#  createuser working_title --createdb
#  rake db:create db:migrate db:seed
#  env RAILS_ENV=test rake db:create db:migrate db:seed

#------------------------------------------------------------
# common
#------------------------------------------------------------

pg: &pg
  adapter:    postgresql
  encoding:   utf8
  template:   template0
  port:       5432
  pool:       25

#------------------------------------------------------------
# environments
#------------------------------------------------------------

development:
  <<: *pg
  host:         127.0.0.1
  username:     working_title
  password:     working_title
  database:     working_title_development

test: &test
  <<: *pg
  host:         127.0.0.1
  username:     working_title
  password:     working_title
  database:     working_title_test
